# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false

matrix:
  include:
    # Make sure to override to "wget" at least once
    - julia: 0.6
      os: linux
      env: BINARYPROVIDER_DOWNLOAD_ENGINE="wget"

    # Test with `busybox` tools
    # NOTE: This disabled for now, as Ubuntu's busybox doesn't support HTTPS.
    # Tested locally to be working on alpine linux, so good enough for now.
    #- julia: 0.6
    #  os: linux
    #  env: BINARYPROVIDER_DOWNLOAD_ENGINE="busybox wget" BINARYPROVIDER_COMPRESSION_ENGINE="busybox tar"

# Ironic.  He could provide binaries for others but not himself...
addons:
  apt:
    packages:
      - curl
      - wget
      - tar
      - gzip
      - busybox

script:
  - if [ -a .git/shallow ]; then
      git fetch --unshallow;
    fi
  - julia --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\" || (!isfile(\"Project.toml\") && !isfile(\"JuliaProject.toml\")); Pkg.clone(pwd()); end"
  - julia --color=yes -e "if VERSION >= v\"0.7.0-\"; Pkg.instantiate(); end"
  - julia --color=yes -e "Pkg.build(\"BinaryProvider\")"
  - julia --check-bounds=yes --color=yes -e "Pkg.test(\"BinaryProvider\", coverage=true)"

after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BinaryProvider")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
